---
title: "Portfolio"
author: "Oussama Abdoun"
format: html
editor: visual
---

::: {.callout-note icon="false"}
## Le formateur

**Ingénieur généraliste et docteur en neurosciences**, je suis chercheur indépendant, consultant en méthodologie de la recherche et formateur en statistiques à destination des praticiens de la recherche.

**Quinze années d'expérience de la recherche** dans des contextes scientifiques variés (electrophysiologie et pharmocologie chez l'animal, robotique, neurosciences cognitives, psychologie sociale et phénoménologie) m'ont donné une large culture de la recherche sur **le cerveau et la cognition**, et une sensibilité aux enjeux spécifiques de ces différents domaines, ce qui me permet de **comprendre très rapidement les objectifs et les questionnements** de mes interlocuteurs.
:::

::: {.callout-tip icon="false"}
## La formation

Je développe et améliore continuellement mes formations en statistique **depuis 2019** auprès d'un public varié de doctorants, postdocs, chercheurs et ingénieurs de recherche lyonnais. Mes cours donnent la part belle à ce que j'aime rencontrer lorsque j'apprends moi-même : des **visualisations** et des **simulations** pour développer l'**intuition**, des **discussions** et **des mises en situation** pour stimuler la réflexion et se remettre en question.

Les statistiques ne sont pas qu'affaire de mathématiques ! Dans mes cours je m'efforce de replacer la technique, parfois exigeante, de l'analyse de données dans le **contexte épistémologique et social** de la recherche scientifique.
:::

<!--# en complément des équations,  des démonstrations Ce qui est considéré comme valide par la communauté est façonné par les conceptions collectives des critères que doivent satisfaire les productions scientifiques: falsificabilité, transparence, reproductibilité... Toutes ces considérations traversent tous mes cours. -->

::: panel-tabset
## FRANÇAIS

# teste

qsd

# et

## ENGLISH

test
:::

\# Statistiques classiques (fréquentistes)

\- estimation: maximum likelihood, confidence interval

\- effect sizes

\- test d'hypothese: p-value & (mis)interpretations

\- the difference between p-value & p(H\|y)

\- error type I & II

\- determining an effect size literature vs. piloting)

\- prevalence of low statistical power

\- base rate of true hypotheses

\- publication bias

\- error type M & S

\- posterior positive rate

\- questionable research practices

\- good practices for reproducibility

\# Linear modeling

Pre-requisite: basic jnowledge in analysis, algebra, and probability theory

1\) Linear modeling

\- Common tests as linear models: correlation, t-tests, chi-square test, non-parametric tests

\- Model fitting: OLS, assumptions, diagnostics

\- ANOVAs: factor coding, hypothesis testing

\- Interactions: coding, post hoc tests

\- Variable selection

\- Generalized models: binomial, poisson, Gamma, ordinal, zero-inflation

2\) Hierarchical modeling with mixed models (LMM)

\- Motivations

\- General structure: non-independence, hierarchy, nested and crossed designs

\- Hypothesis testing

\- Debugging, model specification

3\) Non-linear hierarchical modeling with generalized additive models (GAM)

\- Basic concepts: smooths, penalization

\- Random effects

\- Model diagnostics

\- Non-standard smooths

\- Post hoc tests, visualization

\- Modeling autocorrelation

Non-linear modeling

Pre-requisite: expertise in mixed models

\# Bayesian statistics

\- Frequentist refresher (see course on classical statistics)

\- Elements of probability theory

\- Bayes law

\- Bayesian estimation

\- Numerical simulation of posterior distributions

\- Informative and non-informative priors

\- Eliciting informative priors

\- Posterior-based hypothesis testing

\- Bayes factors, model comparison

\- Default Bayes factors

\- Bayesian model averaging

\- Properties of Bayesian analysis: bias-variance tradeoff & regularization, multiple comparisons, optional stopping

\- The bayesian workflow

\- Prior predictive checks

\- MCMC diagnostics

\- Posterior predictive checks

\- Reporting bayesian analysis

\- Common mistakes & misinterpretations
